platform :ios, '11.0'
use_frameworks!

target 'CatKit' do
  pod 'Alamofire'
  pod 'Quick'
  pod 'Nimble'
  pod 'PactConsumerSwift', :git => 'https://github.com/DiUS/pact-consumer-swift', :branch => 'master'
end

target 'CatKitTests' do
    pod 'Alamofire'
    pod 'Quick'
    pod 'Nimble'
    pod 'PactConsumerSwift', :git => 'https://github.com/DiUS/pact-consumer-swift', :branch => 'master'
end
